services:
  drawdb:
    image: node:20-alpine
    container_name: drawdb
    ports:
      - 41200:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev -- --host --port 80"
    networks:
      - default

networks:
  default:
    driver: bridge
